// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func initializeDB(ctx context.Context) (*sqlx.DB, error) {
	db := NewDatabase()
	return db, nil
}

// wire.go:

var (
	ServiceContainer = wire.NewSet(NewDatabase)
)

func NewDatabase() *sqlx.DB {
	return sqlx.MustConnect("postgres", "host=localhost port=5432 user=ben password=password dbname=tapx sslmode=disable")
}
