apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: app
    image: doodlesbykumbi/skaffold-example
  - name: tests
    image: doodlesbykumbi/skaffold-example
    command: ["reflex"]
    args: ["-r", ".go$", "-R", "mock.go", "-s", "--", "bash", "-c", "go generate ./pkg; go test ./pkg"]
